### ISSUE TITLE
Documentation links on PyPI and in the README are dead

### ISSUE THREAD

**Issue by fprimex** [micheles/plac#16]
Google code page hosting for plac just goes to a 404 now for these two links:

http://plac.googlecode.com/hg/doc/plac.html

http://plac.googlecode.com/hg/doc/plac.pdf

**Comment by micheles** [comment]
plac has been ported to GitHub a long time ago but I forgot to update the links. This has been fixed now:
https://pypi.python.org/pypi/plac/0.9.2
