### ISSUE TITLE
plac 0.9.3 broken in Python 2

### ISSUE THREAD

**Issue by pquentin** [micheles/plac#17]
plac is [now](https://github.com/micheles/plac/commit/9dcab317f7b91623678c29d0aff77c1934b631a0) producing an universal wheel with `use_2to3` which does not appear to work. If you pip install plac in Python 2 you will get the 2to3 fixes, eg. `print('Process %d killed by CTRL-C' % os.getpid(), file=sys.stderr)` withouth `from __future__ import print_function`.

I guess that until you remove 2to3 (which would be a good change!) you will have to use the old way and distribute Python 2 and Python 3 versions.

Thanks

**Comment by micheles** [comment]
I forgot to remove `use_2to3` from the setup.py. I did that and release plac 0.9.4, it should work now.

**Comment by pquentin** [comment]
Thanks!
