### ISSUE TITLE
Remaining Python 2 print

### ISSUE THREAD

**Issue by pquentin** [micheles/plac#18]
`print >> sys.stderr, 'Process %d killed by CTRL-C' % os.getpid()`  in plac_tk.py will break in Python 3.

Thanks

**Comment by micheles** [comment]
Thanks, the test suite is not testing plac_tk.py

**Comment by micheles** [comment]
I made another release fixing that. BTW, are you an user of plac_tk?

**Comment by pquentin** [comment]
No, I'm not using plac_tk.py, it's just that it was the line showing up in the Python 2 bug earlier, so I checked if it was fixed. There could be other errors in plac_tk, I don't know. (By the way, it's refreshing to see Python 2 breaking instead of Python 3 :)
