### ISSUE TITLE
Idea: gh-pages branch

### ISSUE THREAD

**Issue by kirbyfan64** [micheles/plac#20]
It would be neat if you could add a `gh-pages` branch with `plac.html` as `index.html`. That way, one could access the docs online via `micheles.github.io/plac`.

See [here](https://www.thinkful.com/learn/a-guide-to-using-github-pages/) for more info.

**Comment by micheles** [comment]
This is a really good idea. I have known gh-pages for a long time but never thought of using it for plac (even because plac was not on GitHub until recently). Thank you very much!

PS: It is done now.

**Comment by kirbyfan64** [comment]
:+1:
