### ISSUE TITLE
Migrate from imp to importlib

### ISSUE THREAD

**Issue by leezu** [micheles/plac#24]
When running python scripts that depend on `plac_ext.py` under a recent version of Python, a deprecation warning will be issued on every run:

```
/home/leonard/.local/lib64/python3.6/site-packages/plac_ext.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp            

```

**Comment by micheles** [comment]
Thanks for the note. It should be easy to fix. It will be done when I come back from my vacation ;-)

**Comment by perdix** [comment]
I still get the warning! Any further news on this issue?

**Comment by micheles** [comment]
I forgot after going on vacation and two years passed already. It looks like in order to fix it on all supported Python versions I should work more than I thought:
https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path

**Comment by leezu** [comment]
Python 2 is EOL soon. Python 3.4 is EOL already, so only the first part of your linked solution should apply?

**Comment by micheles** [comment]
You have a point. Perhaps I can keep support for Python 2.7 (to help legacy users) and drop support for 3. 0 <= Python <=3.4.

**Comment by micheles** [comment]
I have removed the deprecated importer in the master branch and I plan to make a new release of plac in the coming days.
