### ISSUE TITLE
Specify version of BSD license / include copy with source

### ISSUE THREAD

**Issue by pmlandwehr** [micheles/plac#26]
Hey-lo,

I'm [building a version](https://github.com/conda-forge/staged-recipes/pull/3998) of `plac` using [`conda`](http://conda.pydata.org/) for [conda-forge](http://conda-forge.github.io/). When possible, we try to both include a link to the license file in the `meta.yaml` specification for the build and pin down the exact identity of the license.
Two questions for you:
1. Can you specify whether `plac` is under the BSD 2-Clause or 3-Clause license?
2. Would you consider including a copy of the license with the source tarball the next time you cut a release?

**Comment by micheles** [comment]
On Wed, Sep 20, 2017 at 7:51 AM, Peter M. Landwehr <notifications@github.com
> wrote:

> Hey-lo,
>
> I'm building a version of plac using conda <http://conda.pydata.org/> for
> conda-forge <http://conda-forge.github.io/>. When possible, we try to
> both include a link to the license file in the meta.yaml specification
> for the build and pin down the exact identity of the license.
> Two questions for you:
>
>    1. Can you specify whether plac is under the BSD 2-Clause or 3-Clause
>    license.
>
> It is a 2- clause license

>
>    1. Would you consider including a copy of the license with the source
>    tarball the next time you cut a release?
>
>
Will do.

**Comment by icoxfog417** [comment]
Thank you for the nice tool! I'm waiting for the clarification of the license too.

**Comment by micheles** [comment]
It is done in master. A new release is due shortly.
