### ISSUE TITLE
Unable to run script inside IPython with %run magic command

### ISSUE THREAD

**Issue by rkpatel33** [micheles/plac#27]
Not sure if I am doing something wrong, but I am trying to run this simple test from the IPython prompt where I do most of my dev work but it is not picking up the `-h` flag or any other normal arguments. I am printing the `sys.argv` just for debugging purposes. 

It seems like this should work just like from the bash prompt. Here is my code:

```python
#!/usr/bin/env python
"""
Testing CLI
"""
import sys
import plac

# @plac.annotations(
#     dsn=("Random input", "option", "dsn", int))
def main(dsn):
    print dsn

if __name__ == '__main__':
    print sys.argv
    plac.call(main)
```

Output:

```shell
# IPython prompt
In [43]: %run clitest.py -h
['clitest.py', '-h']
usage: clitest.py [-h] dsn
clitest.py: error: too few arguments
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

In [44]:
```

**Comment by micheles** [comment]
This is fixed in master.
