### ISSUE TITLE
Quick start and API doc

### ISSUE THREAD

**Issue by ppopp** [micheles/plac#29]
Plac looks great, but I never use it because it takes too long to read through the documentation.  When I'm working I really want a quick way to lookup methods and suggested usage.  It's great that there's documentation with all the motivations behind `plac`, and comparisons to other approaches such as `argparse`, but to be useful, I need documentation _without_ all that.  Something efficient to use while I'm in the middle of writing code.

I suggest adding 2 pieces of documentation which are separate from the existing documentation.

1. Quick Start
This would show the top N common uses. For example, these uses cases could be covered:
    - How to support a program with a single variable
    - How to support a program with multiple variables
    - How to support a program with optional variables
    - How to support a program requiring default values and types

2. API Doc
     Something in the style of https://docs.python.org/3/library/argparse.html where the doc follows other python documentation in style and organization. It should have:
      - A short description of what plac does
      - A handful of examples
      - Documentation of the useful functions, classes and methods.

**Comment by kirbyfan64** [comment]
IMO plac's docs are actually pretty fantastic. If you skip the first 3 or so paragraphs explaining the rationale, it's pretty hands-on: the code examples are basically the quick start you want.

AFAIK the API surface isn't that large, so having a full set of API docs might be kind of worthless.

**Comment by ppopp** [comment]
Thanks for the tip on skipping the first 3 paragraphs. I see there that you begin to get nicely ordered use cases.  And fair point about the API docs being unnecessary. I can't claim to have much insight into the API, though I generally do like to have one place that describes all optional parameters, particularly for the `annotation` method.  Albeit this does show up in the existing plac documentation, it's just rather buried and in a non-obvious spot. 

I still think there can be a more succinct docs which also reflect how many other python packages are documented. There is value in having your docs look like others' docs in that it allows people to more easily navigate the docs and thus utilize the software.

For instance, one thing that slows me down every time is when I look at the `Scripts with required arguments` section. http://micheles.github.io/plac/#scripts-with-required-arguments. The first example uses `sys.argv`! So I'm looking at this code thinking _wheres plac?_ Then I see all this text around it talking about what a parser should and shouldn't be.  It's a time drag having to dig in and spot the examples.

And I'm not saying that the existing doc is flawed. It's very in-depth and does a great job of talking about all the motivations. But I do think this package is in desperate need of a succinct __Quick Start__ to accompany the existing documentation.

**Comment by ppopp** [comment]
# Plac
The easiet command line parser for python.

Plac makes parsing command line arguments a breeze, requiring you to write the least amount of code while handling the most common use cases.

### Installation
```
pip install plac
```

### Basic Usage
```
# quickstart1.py

def main(positional_arg, keyword_arg='foo'):
    print(positional_arg)
    print(keyword_arg)

if __name__ == '__main__':
    import plac
    plac.call(main)
```

```
$ python quickstart1.py -h
usage: quickstart1.py [-h] positional_arg [keyword_arg]

positional arguments:
  positional_arg
  keyword_arg     [foo]

optional arguments:
  -h, --help      show this help message and exit
```


### Argument Annotations
Argument annotations allow you to set help text, argument kinds, abbreviations, argument types, choices and metavars.

#### Using python2 or python3
```
# quickstart2.py

import plac

@plac.annotations(
    foo=("A positional argument", 'positional', None, str, ['choice1', 'choice2'], 'FOO_METAVAR'),
    bar=("A flag", 'flag', 'b'),
    baz=("A kewyword argument", 'option', 'z'))
def main(foo, bar=False, baz=None):
    print('foo {0}'.format(foo))
    print('bar {0}'.format(bar))
    print('baz {0}'.format(baz))

if __name__ == '__main__':
    plac.call(main)
```
```
$ python quickstart2.py -h
usage: quickstart2.py [-h] [-b] [-z None] FOO_METAVAR

positional arguments:
  FOO_METAVAR          A positional argument

optional arguments:
  -h, --help           show this help message and exit
  -b, --bar            A flag
  -z None, --baz None  A kewyword argument
```

#### Using python3
Python3 introduced function annotations which can be used in place of the plac decorator.

```
# quickstart3.py

import plac

def main(
        foo: ("A positional argument", 'positional', None, str, ['choice1', 'choice2'], 'FOO_METAVAR'),
        bar: ("A flag", 'flag', 'b')=False,
        baz: ("A kewyword argument", 'option', 'z')=None):
    print('foo {0}'.format(foo))
    print('bar {0}'.format(bar))
    print('baz {0}'.format(baz))

if __name__ == '__main__':
    import plac
    plac.call(main)
```

```
$ python3 quickstart3.py
usage: quickstart3.py [-h] [-b] [-z None] FOO_METAVAR

positional arguments:
  FOO_METAVAR          A positional argument

optional arguments:
  -h, --help           show this help message and exit
  -b, --bar            A flag
  -z None, --baz None  A kewyword argument
```

### Further Reading
<http://micheles.github.io/plac/#scripts-with-default-arguments>

**Comment by micheles** [comment]
Done in master
