### ISSUE TITLE
SystemExit Error when ran inside a Jupyter Notebook

### ISSUE THREAD

**Issue by ursachi** [micheles/plac#30]
since plac is a wrapper over argparse, it seems there is an issue when running it inside a Jupyter Notebook. 

Here's an [example](https://github.com/explosion/spacy/blob/master/examples/training/train_ner.py) from spacy tutorials

At runtime, I get the following error:

> usage: ipykernel_launcher.py [-h] [-m None] [-o None] [-n 100]
ipykernel_launcher.py: error: unrecognized arguments: -f /Users/<my_user>/Library/Jupyter/runtime/kernel-b09996b6-dd81-4a9a-8619-c99b6c9a4919.json
> An exception has occurred, use %tb to see the full traceback.

> SystemExit: 2

> /Users/<my_user>/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2918: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

I found a [workaround](https://stackoverflow.com/questions/48796169/how-to-fix-ipykernel-launcher-py-error-unrecognized-arguments-in-jupyter#48798075) for argparse on stackoverflow, but I am not sure if it can be applied to plac.

**Comment by micheles** [comment]
This is now fixed in master.

**Comment by jframe9** [comment]
I found the same question, but i don't know how to deal it...

**Comment by micheles** [comment]
Install plac 1.1.0 and that issue should have disappeared

**Comment by jframe9** [comment]
> Install plac 1.1.0 and that issue should have disappeared

yeah！Because I use ipython which is differernt from IDE, I found that if I add one parameter of it，the problem  has been solved.
