### ISSUE TITLE
Please mark the 'multiprocessing' dependency as python 2.4/2.5 only

### ISSUE THREAD

**Issue by yurivict** [micheles/plac#32]
See this line: https://github.com/micheles/plac/blob/master/setup.py#L40

PyPI description says that it only exists for python 2.5/2.5: https://pypi.org/project/multiprocessing/

**Comment by refi64** [comment]
If you look at the require function in setup.py, you can see that it tries to import the module and only adds it to the dependency list if the import fails. If it's trying to download it for you, try importing multiprocessing manually and see if you get any errors.

**Comment by yurivict** [comment]
There's a special syntax for this right in the ```setup_requires``` line.
I believe you can write ```;python<2.7``` or something like that.

**Comment by refi64** [comment]
That was probably written before python_version was a thing (it seems to be a newer-ish addition, pip 6.0 added it and it was specified in a 2015 PEP).

That being said, I think all the Python versions that would have needed these external backports have been EOL for quite some time now?

**Comment by yurivict** [comment]
Yes, they EOLed.
Just remove ```multiprocessing```.

**Comment by micheles** [comment]
This is done in master, but do you want a new release just for this fix?

**Comment by yurivict** [comment]
> This is done in master, but do you want a new release just for this fix?

No need for a release.
Thank you!
