### ISSUE TITLE
Help confusing when default value is empty string

### ISSUE THREAD

**Issue by isaacto** [micheles/plac#36]
Plac shows default argument as argparse metavar.  But when argparse is given a metavar of an empty string, the results look more like a flag than an option, which is confusing.  (To be fair, there are differences, but very hard to spot.)

```
$ cat test_plac.py 
#!/usr/bin/env python
def func(opt: ('opt', 'option', 'o') = ''):
    print(opt)
import plac
plac.call(func)
$ ./test_plac.py -h
usage: test_plac.py [-h] [-o]

optional arguments:
  -h, --help   show this help message and exit
  -o , --opt   opt
```

**Comment by micheles** [comment]
But what would you propose to do? Also notice that plac is using argparse under the hood, so the formatting of the help message is the argparse formatting, there isn't much that I can do.

**Comment by isaacto** [comment]
I'd argue that argparse never intend that metavar should show the default value, so in the view of argparse this is not a bug.  I like the idea (because it means the help message can be much shorter), but if there is corner cases like this, I think it should be Plac to adjust.

My suggestion is to pass '""' (a string containing a pair of double quotes) as metavar if the default is the empty string.  That would make it indistinguishable from a default argument which is really a pair of double-quotes.  I think it is acceptable (because such defaults are rare), but if you really think it should be addressed the double quote character could be escaped in the metavar.
