### ISSUE TITLE
When kwargs are used, option values cannot have "="

### ISSUE THREAD

**Issue by isaacto** [micheles/plac#38]
I know this is painful to fix, but I call it a bug anyway because it is very unexpected: users would think it easy to know that "--opt", requiring one option, will take the "abc=" below.

```
$ cat test_plac.py 
#!/usr/bin/env python
def func(opt: ('opt', 'option', 'o') = 'foo', **kw: ('kw',)):
    print(opt, kw)
import plac
plac.call(func)
$ python test_plac.py --opt abc=
usage: test_plac.py [-h] [-o foo] [kw [kw ...]]
test_plac.py: error: argument -o/--opt: expected one argument
```

**Comment by micheles** [comment]
Fixed in master, https://github.com/micheles/plac/commit/f3e28a6868004d3a424c6bd14d3327f216733bdf
