### ISSUE TITLE
When kwargs are used, unrecognized arguments are not notified

### ISSUE THREAD

**Issue by isaacto** [micheles/plac#39]
Without kwargs, unrecognized arguments leads to an error notifying the user that the command used is wrong.  But with kwargs...

```
$ cat test_plac.py 
#!/usr/bin/env python
def func(**kw: ('kw',)):
    print(kw)
import plac
plac.call(func)
$ ./test_plac.py foo
{}

```

**Comment by micheles** [comment]
Fixed in master, https://github.com/micheles/plac/commit/b040557f56af7d7cf2867ae04c59ce0a184e20d8
