### ISSUE TITLE
Improvement: Documentation is hard to read

### ISSUE THREAD

**Issue by fabianoengler** [micheles/plac#41]
The documentation is bit hard to read, mostly due to it's presentation/templating I guess, which is very off from the expected python standards used in the community.

I am attaching some screenshots for comparison, showing the extremes of a 4k desktop and a mobile screen:

# Plac:
## desktop
![Screenshot_2019-10-20 plac rst](https://user-images.githubusercontent.com/26912527/67171517-d4583680-f38d-11e9-95d5-5b889cf31b50.png)

## mobile
![Screenshot_2019-10-20 plac rst(1)](https://user-images.githubusercontent.com/26912527/67171527-e639d980-f38d-11e9-80a0-1b569dda10b2.png)

---------------

# Click:
https://click.palletsprojects.com/en/7.x/options/

## desktop

![Screenshot_2019-10-20 Options — Click Documentation (7 x)](https://user-images.githubusercontent.com/26912527/67171599-3e70db80-f38e-11e9-96b0-7e7ca29330c6.png)

## mobile
![Screenshot_2019-10-20 Options — Click Documentation (7 x)(1)](https://user-images.githubusercontent.com/26912527/67172768-015b1800-f393-11e9-841e-b569a6ff3e9f.png)

---------------

# Scrapy:
https://docs.scrapy.org/en/latest/intro/tutorial.html

## desktop
![Screenshot_2019-10-20 Scrapy Tutorial — Scrapy 1 7 3 documentation](https://user-images.githubusercontent.com/26912527/67171707-9dceeb80-f38e-11e9-8f9e-10f7003315c2.png)

## mobile
![Screenshot_2019-10-20 Scrapy Tutorial — Scrapy 1 7 3 documentation(1)](https://user-images.githubusercontent.com/26912527/67171713-a6bfbd00-f38e-11e9-95d5-f6217a23ca9b.png)

---------------

Requests:
https://requests.kennethreitz.org/en/master/user/advanced/

## desktop
![Screenshot_2019-10-20 Advanced Usage — Requests 2 22 0 documentation(1)](https://user-images.githubusercontent.com/26912527/67171645-5d6f6d80-f38e-11e9-923b-dd06c9a667e3.png)

## mobile
![Screenshot_2019-10-20 Advanced Usage — Requests 2 22 0 documentation(2)](https://user-images.githubusercontent.com/26912527/67171741-c8b93f80-f38e-11e9-94e5-72d85d5a64eb.png)

---------------

The counter examples seem so more easier to follow and pleasant to read, both on mobile and on larger screens (except for requests on mobile, which is a little bit off).

The main points for improvement I identified are:
- Use a sensible max witdh
- Use syntax highlighting for code samples
- Perhaps a little larger font size and increased spacing between lines

The pdf version has the same issues, except for the fixed margin, which helps on desktop, but it is still not responsive (friendly on a range of screens).

I personally love this project and how it scales down, but at a first contact I did find it very welcoming for the questions I had that the README didn't answer and I almost skipped it. I'm glad I stayed but I wonder if the same happened to others. I would love to see this project gaining more visibility and adoption and I believe a more pleasant documentation could help.

I can see a fair amount of time was already spent on the documentation *content*, it's just that its current presentation doesn't do it justice :neckbeard: .

I think the https://readthedocs.org/ project already has a very good default template that addresses most of the issues I am pointing. They use sphinx, which support rst format that plac is already using, so I believe the migration would be fairly simple.

If the issue seems fair and help is wanted, let me know :wink:

**Comment by micheles** [comment]
I was using readthedocs for the decorator module and moved away from it because of an annoying bug (at each new release the documentation was still pointing to an old release). The CSS for the plac documentation was contributed. I will have to think of something (I have also considered MkDocs in the past).

**Comment by micheles** [comment]
The documentation is now in sphinx: http://micheles.github.io/plac/ (!)
And plac 1.1.3 has been released (there are no 1.1.1 and 1.1.2 releases, they were false starts before I managed to commit all the files relevant for sphinx).
