### ISSUE TITLE
Multiline help string should be de-dented. 

### ISSUE THREAD

**Issue by ialbert** [micheles/plac#45]
Thanks for the great tool. It is very enjoyable to use.

One problem that impacts usability is that multiline docstrings will be printed indented in the automatically generated help. This basically forces us to only have single quote docstrings which does two things, limits help to one line but also interferes with code formatting standards. Many tools will reformat docstrings to triple quote blocks. 

I was wondering if you have plans to add an automatic de-denting of the docstring, or if not if you could point me to the code where I could add this de-denting myself in a local fork of the code.

thanks.

**Comment by micheles** [comment]
This is implemented now in master and you can try it. It will part of the next release of plac.

**Comment by ialbert** [comment]
Thank you @michele, much appreciated.
