### ISSUE TITLE
broken links in documentation

### ISSUE THREAD

**Issue by BrettMoan** [micheles/plac#46]
There are two broken links in the section http://micheles.github.io/plac/#plac-vs-argparse

two links with the text  advanced usage document  link to a non-existent link [http://micheles.github.io/plac/in-writing](http://micheles.github.io/plac/in-writing) 

I assume the link address needs corrected to http://micheles.github.io/plac/#implementing-subcommands

**Comment by BrettMoan** [comment]
would need to lookup the syntax for referncning a heading in the same document, but here is the problem:

https://github.com/micheles/plac/blame/master/doc/plac_core.rst#L784

**Comment by emeti** [comment]
Another broken link in http://micheles.github.io/plac/ is https://www.welton.it/articles/scalable_systems , After going through Welton's site I figured out it should be https://www.welton.it/articles/scalable_systems.html  
and if the rst is used to generate the doc then fix requires change of https://github.com/micheles/plac/blame/master/doc/plac_core.rst#L775

**Comment by micheles** [comment]
The links are fixed now
