### ISSUE TITLE
lack of simple documentation limits the reach of this tool 

### ISSUE THREAD

**Issue by ialbert** [micheles/plac#48]
I really like this library and have been using it regularly. 

While doing so made me realize several substantial limitations in the way this tool is documented and explained, that, in my opinion, is perhaps the greatest hindrance to the acceptance of the tool.

Whenever I forget the exact invocation or I want to look up more details I find that the documentation website at

https://micheles.github.io/plac/

is very tedious and non-supportive to help get things done. It has a long-winded writing style and goes into various tangential issues on the rationale. Overall it fails to support the practical use cases that a programmer needs and wants. Give us examples on how to use the tool.

Imagine that you are using a library and trying to look up the use cases, instead the documentation writer continuously talks about the rationale then and produces examples that are either too simplistic or too complicated - that is exactly how I feel reading the docs.  

The entire library is meant to demonstrate  **the importance of scaling down"** yet the help and documentation is anything but scaling down. 

In the eagerness to demonstrate how easy is to use the library everything is documented in several, alternative and different ways - only adding to the confusion. 

The actual feature that everyone will eventually use for anything but the most trivial code is  listed deep down in the "More features" section, this is the line I have to constantly find to remind myself of the order of annotations:

    (help, kind, abbrev, type, choices, metavar)

The entire documentation should start with a simple example like so

```
@plac.annotations(
    fname=("input file", "option", "f", str, None, "PATH"),
    count=("word count", "option", "c", int, None, "INT"),
)
def run(fname, count):
    pass
```

perhaps adding a few variants to cover the main use-cases

so that people can look that up and move on and not have to continuously scour through pages and pages of content they don't care about.

**Comment by micheles** [comment]
You could have been more diplomatic. Having said that, I wonder about the future of plac.

It has just reached its tenth birthday, being first published in June 2010. I has a lot of users, more than I expected, and https://libraries.io/pypi/plac tells me that there are 596 repositories dependent on it.

I do not use it. I think it is too big, the only features that I need in my everyday life are the simplest ones, and even for that use case I cannot remember the order of the annotations, so I wrote another tool that it is much simpler and does not require annotations (plac annotations were an acceptable idea 10 years ago, but now Guido has pronounced that Python 3 annotations should be used as type annotations only).

Should I deprecate plac? I have maintained it for the last 5 years without using it, just for the benefit of my users. Having to support their questions is becoming more and more costly. I do not see myself working again on its code base  and I have done only cosmetic changes in the last 5 years.
I am not sure what would be a better service for my users, deprecating or just keeping it as it is,
essentially frozen, with a cosmetic release every year or two.

If somebody wants to step up as the maintainer of plac I am willing to give to him (or her)
the permissions on the repository. 

If you want to make a Pull Request on the documentation I will accept it.

Suggestions about the future of the tool are accepted too.

**Comment by micheles** [comment]
Apparently the biggest project using plac is this one: https://libraries.io/github/explosion/spaCy.
After some thinking, I decided NOT to deprecate plac for the moment.
I has some things to do pending, so I finished them, made a new release (1.2.0) and added a new section to the documentation: https://micheles.github.io/plac/#for-the-impatient

**Comment by ialbert** [comment]
Thank you for your consideration. Indeed I should have been more diplomatic. My apologies if my message came through too rude.

The new section on the impatient is very useful, exactly what the documentation needed, a quick and simple copy-paste code that demonstrates how easy it is to create a command-line interface.

Thank you for the work on plac it is an awesome library with a genius idea.

**Comment by RuABraun** [comment]
I love this library and have been using it for years. To me the chief selling point of this library is that you don't have to define arguments twice. The decorator stuff means you do.

Could someone help me understand why the decorator syntax is preferred? @ialbert And why if one does that one would use this library over click?

**Comment by ialbert** [comment]
the no defintion method works just fine, and perhaps I should make that use case evident

I found that very frequently, I need just one extra definition and then have to reach for the decorators anyway.

So I thought let's show the most common use case as well

For me the best feature of plac is that I can package it with my code, and thus it makes code with no dependencies not even  plac.

historically plac probably proceeds click, 

I will also say that I had some really nasty experiences with click some years ago when it raised all manner of weird encoding errors all the while it was badmouthing Python and claiming it was Python's fault that somehow Python 3 is fundamentally broken. That set the wrong tone for me.

maybe they fixed that since, but I never looked at click after that,
