### ISSUE TITLE
'choices' do not show up in help message.

### ISSUE THREAD

**Issue by bigsipper** [micheles/plac#50]
I would expect this decoration
@plac.opt('n',     "Number of iterations", type=int, choices=[100,200] )
to show the choices on the help message (like it does using argparse directly)

Example:
`@plac.pos('gds',   "GDSII input file name", type=Path)
@plac.opt('out',   "Optional output directory", type=Path)
**@plac.opt('n',     "Number of iterations", type=int, choices=[100,200] )**
@plac.flg('debug', "Enable debug mode")
def main( 
   gds,        # required
   out='.',    #optional. Default to cwd. 
   n=100,      #optional. Example of int.
   debug=False,#optional. Example of boolean.
   ): 
   ''' What does this program not do? '''   # Displayed in usage message.

   print(f"-gds {gds}")
   print(f"-out {out}")
   print(f"-n {n}")
   print(f"-debug {debug}")

   return
`

But output does not show choices  100, 200 :

> ...
optional arguments:
  -h, --help       show this help message and exit
  -o ., --out .    Optional output directory
  **-n 100, --n 100  Number of iterations**
  -d, --debug      Enable debug mode

...

**Comment by micheles** [comment]
The issue is that `n` has a default. plac chooses to display the default over the choices in the help message. If you remove the defaults you will get the choices:
```
$ python x.py -h
usage: x.py [-h] [-o OUT] [-n {100,200}] [-d] gds

What does this program not do?

positional arguments:
  gds                   GDSII input file name

optional arguments:
  -h, --help            show this help message and exit
  -o OUT, --out OUT     Optional output directory
  -n {100,200}, --n {100,200}
                        Number of iterations
  -d, --debug           Enable debug mode
```
Displaying the default looks nicer to me than displaying the choices, but it is just a matter of personal preference.
